name: ArranStevenson
favicon: null
layout_spectrum: 0.8291234998032451
typography_spectrum: 0.6577418823726475
title: Arran Stevenson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9333409457467496
  lightness: 0.0019713384099304676
  saturation: 0.22852631215937436
  rhythmicContrast: 0.6665796365123242
purpose: []
